### ISSUE TITLE
web server not reporting online data

### ISSUE THREAD

**Issue by mlp6** [mlp6/ADPL#91] opened 2016-11-17 18:02 UTC

**Comment by mlp6** [comment] 2016-11-20 22:34
Web server was down; inspecting the screen session had this error message:

```
New Message
/home/bitnami/ADPL/software/logging/handle-device.js:26
                        realData.temp = realData.data.split(",")[d].split(":")[1].replace(/\s+/g, '');
                                                                                 ^

TypeError: Cannot read property 'replace' of undefined
    at EventSource.<anonymous> (/home/bitnami/ADPL/software/logging/handle-device.js:26:61)
    at emitOne (events.js:77:13)
    at EventSource.emit (events.js:169:7)
    at _emit (/home/bitnami/ADPL/software/logging/node_modules/eventsource/lib/eventsource.js:181:17)
    at parseEventStreamLine (/home/bitnami/ADPL/software/logging/node_modules/eventsource/lib/eventsource.js:196:9)
    at IncomingMessage.<anonymous> (/home/bitnami/ADPL/software/logging/node_modules/eventsource/lib/eventsource.js:159:11)
    at emitOne (events.js:77:13)
    at IncomingMessage.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at IncomingMessage.Readable.push (_stream_readable.js:111:10)
    at HTTPParser.parserOnBody (_http_common.js:127:22)
    at TLSSocket.socketOnData (_http_client.js:322:20)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at TLSSocket.Readable.push (_stream_readable.js:111:10)
```

Manually-restarted the web server... will keep an eye on this.

**Comment by suyashkumar** [comment] 2016-11-21 00:54
hmmm it seems that `realData.data.split(",")[d].split(":")[1]` is undefined. It seems you (or perhaps me?) added a comment about how we're parsing non-traditional JSON here--we should probably only do that for messages we're sure have the formatting we expect. Other messages (like system messages) may be published on this stream. I'll add in some safety/error handling logic here to catch and describe these errors better :)

**Comment by suyashkumar** [comment] 2016-11-21 00:56
I will say, however, that this is likely unrelated to the "not reporting online data" problem, as in that case the server was still running but not receiving or acting upon new messages on the particle stream.

**Comment by suyashkumar** [comment] 2016-11-21 00:56
Also it seems that all these messages are "TEMPS" messages so we shouldn't have to gate further. I will add more safety logic in here though.

**Comment by mlp6** [comment] 2016-11-22 01:24
Another error associated with the server going offline:
```
{ [Error: socket hang up] code: 'ECONNRESET' }
undefined
undefined:1
undefined
^

SyntaxError: Unexpected token u
    at Object.parse (native)
    at Request._callback (/home/bitnami/ADPL/software/logging/api/ondemand.js:16:22)
    at self.callback (/home/bitnami/ADPL/software/logging/node_modules/request/request.js:186:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/home/bitnami/ADPL/software/logging/node_modules/request/request.js:845:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at TLSSocket.socketOnEnd (_http_client.js:305:9)
    at emitNone (events.js:72:20)
    at TLSSocket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:923:12)
    at nextTickCallbackWith2Args (node.js:458:9)
    at process._tickCallback (node.js:372:17)
```

**Comment by suyashkumar** [comment] 2016-11-29 00:01
It seems that this socket reset is probably an express/routing issue (someone fired off a request and then closed it before we could write a response). I added in some express middleware error handling in 518064e44b51ba68433402645e38d0dd0de16278 to address this and prevent the server from crashing in such circumstances.

**Comment by suyashkumar** [comment] 2016-11-29 00:03
Further investigation is probably still warranted into some of the root causes of the issues we see here if they crop up again. Again i think there are several different issues here, but some of these could be one off (I've noticed that we are getting a lot of bot spam on various routes as well looking through the logs).

**Comment by suyashkumar** [comment] 2016-12-09 05:26
Two errors this time. The first seems like a DNS issue that should get resolved on retry. The second one is an error in parsing JSON from a call to particle's api to get real time valve status. I'll add in logic to catch this better! 
```
{ Error: getaddrinfo ENOTFOUND api.particle.io api.particle.io:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'api.particle.io',
  host: 'api.particle.io',
  port: 443 }
undefined
undefined:1
undefined
^

SyntaxError: Unexpected token u in JSON at position 0
    at Object.parse (native)
    at Request._callback (/home/bitnami/ADPL/software/logging/api/ondemand.js:16:22)
    at self.callback (/home/bitnami/ADPL/software/logging/node_modules/request/request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/home/bitnami/ADPL/software/logging/node_modules/request/request.js:845:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1020:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Closed as completed** 2018-05-21 22:06 UTC
Labels: bug
